// generated by stringer -type=slotType; DO NOT EDIT

package parc

import "fmt"

const _slotType_name = "slotAltslotNonTerminalslotTerminalslotReturnslotFinish"

var _slotType_index = [...]uint8{0, 7, 22, 34, 44, 54}

func (i slotType) String() string {
	if i < 0 || i+1 >= slotType(len(_slotType_index)) {
		return fmt.Sprintf("slotType(%d)", i)
	}
	return _slotType_name[_slotType_index[i]:_slotType_index[i+1]]
}
